/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gonzaloflorez.gonzalo.facturadeventa.infrastructure.in;

import com.gonzaloflorez.gonzalo.facturadeventa.infrastructure.out.FacturaVentaMySQLRepository;

/**
 *
 * @author camper
 */
public class FacturaVentaViewAll extends javax.swing.JPanel {

    /**
     * Creates new form FacturaVentaViewAll
     */
    public FacturaVentaViewAll() {
        initComponents();
        FacturaVentaMySQLRepository facturaVentaConsole = new FacturaVentaMySQLRepository();
        facturaVentaConsole.MostrarFacturaVenta(TbTotalFacturas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TbTotalFacturas = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        TbTotalFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TbTotalFacturas);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbTotalFacturas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
